### ISSUE TITLE
How to return indices, instead of vec of points?

### ISSUE THREAD

**Issue by saedrna** [thinks/poisson-disk-sampling#2]
Is it possible? I'm not quite understanding the algorithm, is this what I want?

```cpp
  auto samples = std::vector<VecT>{};
  auto active_indices = std::vector<std::uint32_t>{};
  auto local_seed = seed;
```

**Comment by thinks** [comment]
Hi, not sure I understand which indices you want to return? I'm sure the code can be modified to do it, the algorithm is not that complex.

**Comment by saedrna** [comment]
I think I misunderstand what the code does.
It seems that it generate random points, but what I want to do is to sample some points from point clouds.

**Comment by thinks** [comment]
You might be able to re-use some ideas from the paper referenced in README.md, such as creating a grid structure for neighbor queries, but you are right that this is a separate topic and I'm sure there is plenty of literature on how to deal with it.
