### ISSUE TITLE
dimension limits

### ISSUE THREAD

**Issue by xarthurx** [thinks/poisson-disk-sampling#5]
It seems that once the dimension goes up to 10, there will be a memory problem cause by this function:

```
  static std::vector<std::int32_t> GetCells_(const IndexType& size) {
    // Initialize cells with value -1, indicating no sample there.
    // Cell values are later set to indices of samples.
    const auto linear_size =
        std::accumulate(std::begin(size), std::end(size), std::size_t{1},
                        std::multiplies<std::size_t>());
    return std::vector<CellType>(linear_size, -1);
  }
};

```

In general, the current method is limited by the grid size it can create...

**Comment by thinks** [comment]
Yes, we create a dense grid for lookups, so it quite quickly becomes a
problem, especially for higher dimensions. Not much to do about that with
the current method. Are you aware of any alternative methods that don't
have this limitation?

/ T

**Comment by xarthurx** [comment]
Hi, yes.
After I encounter this issue, I continue the search and found this:
http://www.cemyuksel.com/cyCodeBase/soln/poisson_disk_sampling.html

Which also provide implementation code and can nicely generate larger dimension points (in my case, around 20D, works very smooth).

Hope this helps.

**Comment by thinks** [comment]
Thanks, I will check it out!

**Comment by thinks** [comment]
The sample elimination method looks very nice!
